# Generated by Django 5.2.5 on 2026-02-26 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Connection statuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_message_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'follow_up_message_id'],
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'message_id'],
            },
        ),
        migrations.CreateModel(
            name='SentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_link', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_connections', to='tracker.connectionstatus')),
                ('follow_up_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_connections', to='tracker.followupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='followupmessage',
            constraint=models.UniqueConstraint(fields=('follow_up_message_id', 'user'), name='unique_follow_up_message_id_per_user'),
        ),
        migrations.AddConstraint(
            model_name='messagetype',
            constraint=models.UniqueConstraint(fields=('message_id', 'user'), name='unique_message_id_per_user'),
        ),
    ]
