# Generated by Django 5.2.5 on 2026-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentconnection',
            name='follow_up_message_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sentconnection',
            name='follow_up_message_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sentconnection',
            name='follow_up_message_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
